#!/usr/bin/env bash

echo "EXECUTING run_autograder from sample-java-mvn-autograder"

base=/autograder
if [ "$#" -eq 1 ]
then
   base=$1
fi

function number_matching_files {
    if [ ! "$#" -eq 1 ]
    then
       echo "Illegal number of parameters to ${FUNCNAME[0]}"
    fi
    ls 2>/dev/null -Ubad1 -- $1 | wc -l
}


function make_flat_student_submission_dir {
    mkdir -p ${base}/STUDENT-WORK
    cp -r ${base}/submission/* ${base}/STUDENT-WORK

    pushd ${base}/STUDENT-WORK

    number_top_files=$( number_matching_files "./*"  )
    top_files=( ./* )
    top_file="${top_files[0]}"

    if [ \( $number_top_files -eq 1 \) -a \( "$top_file" != "" \) -a \( -d "${top_file}" \) ];
    then
	mv ${top_file}/* .
	mv ${top_file}/.* .
	rmdir ${top_file}
    fi
    popd	
}

make_flat_student_submission_dir 

if [ -f grade-java.sh ];
then
    chmod u+x grade-java.sh
    ./grade-java.sh "$1"
fi
