#!/usr/bin/env bash


cd /autograder/git-repo/gradescope-autograder-samples-java-mvn/

# Make sure student has the right package name in their file
cp /autograder/submission/IntList.java src/main/java/com/gradescope/intlist

mvn -q compile
mvn -q test
mvn -q exec:java > /autograder/results/results.json
